name: Linting, Testing, Building

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run linting and formatting
        run: yarn lint

      - name: Build TypeScript
        run: yarn build

      - name: Check build artifacts
        run: ls -la dist/

      - name: Validate Playwright metadata
        run: yarn validate:playwright

      - name: Run tests with coverage
        run: yarn test:coverage

      - name: Generate coverage summary for PR
        if: github.event_name == 'pull_request'
        run: yarn coverage:summary

      - name: Check coverage thresholds
        run: yarn coverage:check

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Archive coverage artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: |
            coverage/
            !coverage/.nyc_output/
          retention-days: 30
